{% set version = "0.3.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-autostats
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/autostats_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/autostats/autostats_{{ version }}.tar.gz
  sha256: 28c23a72aa57fe52365b874b4eb9b030f2ff69813f5ab7b996a0733dffb9c1fa

build:
  merge_build_host: true  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-foci
    - r-xicor
    - r-agtboost
    - r-broom
    - r-data.table
    - r-dials
    - r-doparallel
    - r-dplyr
    - r-flextable
    - r-forcats
    - r-framecleaner
    - r-ggeasy
    - r-ggplot2
    - r-ggthemes
    - r-gtools
    - r-janitor
    - r-jtools
    - r-lubridate
    - r-magrittr
    - r-nnet
    - r-parsnip
    - r-party
    - r-patchwork
    - r-presenter
    - r-purrr
    - r-readr
    - r-recipes
    - r-recosystem
    - r-rlang
    - r-rlist
    - r-rsample
    - r-stringr
    - r-tibble
    - r-tidyr
    - r-tidyselect
    - r-tune
    - r-workflows
    - r-xgboost
    - r-yardstick
  run:
    - r-base
    - r-foci
    - r-xicor
    - r-agtboost
    - r-broom
    - r-data.table
    - r-dials
    - r-doparallel
    - r-dplyr
    - r-flextable
    - r-forcats
    - r-framecleaner
    - r-ggeasy
    - r-ggplot2
    - r-ggthemes
    - r-gtools
    - r-janitor
    - r-jtools
    - r-lubridate
    - r-magrittr
    - r-nnet
    - r-parsnip
    - r-party
    - r-patchwork
    - r-presenter
    - r-purrr
    - r-readr
    - r-recipes
    - r-recosystem
    - r-rlang
    - r-rlist
    - r-rsample
    - r-stringr
    - r-tibble
    - r-tidyr
    - r-tidyselect
    - r-tune
    - r-workflows
    - r-xgboost
    - r-yardstick

test:
  commands:
    - $R -e "library('autostats')"           # [not win]
    - "\"%R%\" -e \"library('autostats')\""  # [win]

about:
  home: https://harrison4192.github.io/autostats/, https://github.com/Harrison4192/autostats
  license: MIT
  summary: Automatically do statistical exploration. Create formulas using 'tidyselect' syntax, and then determine cross-validated model accuracy and variable contributions using 'glm' and 'xgboost'. Contains additional helper functions to create and modify formulas. Has a flagship function to quickly determine relationships
    between categorical and continuous variables in the data set.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
